// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "GRIDFIELD_BULK_MANAGER.BULKACTION_EMPTY_SELECT": "Vi devas elekti almenaŭ unu rilordon.",
    "GRIDFIELD_BULK_MANAGER.CONFIRM_DESTRUCTIVE_ACTION": "La datumoj perdiĝos porĉiame. Ĉu daŭrigu?",
    "GRIDFIELD_BULK_UPLOAD.PROGRESS_INFO": "Alŝutas %s dosiero(j)n. %s farita(j). %s eraro(j)."
});
}