// This file was generated by silverstripe/tx-translator from client/lang/src/sl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "GRIDFIELD_BULK_MANAGER.BULKACTION_EMPTY_SELECT": "Izbrati morate vsaj en zapis.",
    "GRIDFIELD_BULK_MANAGER.CONFIRM_DESTRUCTIVE_ACTION": "Želite dokončno izbrisati podatke?",
    "GRIDFIELD_BULK_UPLOAD.PROGRESS_INFO": "V teku je prenos %s datotek(e). %s zaključenih. %s napak(e)."
});
}